### ISSUE TITLE
Music player above menu bar

### ISSUE THREAD

**Issue by Tay0108** [AirJumperYT/AirJumperYT.github.io#1]
As you can see on the screenshot music player is going above menu bar. Probably z-index bug.
<img width="869" alt="Screenshot 2020-05-20 at 14 53 30" src="https://user-images.githubusercontent.com/10603901/82448298-cf856d80-9aa9-11ea-9a87-04463fdfea95.png">

**Comment by AirJunio** [comment]
@Tay0108 Yeah, thanks. I've already fixed it ;D

**Comment by Tay0108** [comment]
Great job, closing this issue then ;)
